### PR TITLE
Merging dev to main

### PR DESCRIPTION
**Pull request by rmcguire6**
Want to push these changes to production.

### CODE REVIEW

**Comment by ArturoDucasse** [comment]
But they are already in the main branch, notice that between the three commits one is me accepting a pull request that has both Dan and Machu changes.  

If I'm missing something, please let me know.

**Review by JessieFrance — APPROVED** [review]
I think this looks good. Thank you Regina!

**Comment by JessieFrance** [comment]
Arthur I think that you raise a good question (and I had to double check this), but I think this PR is okay to merge.

To double check this, I cloned the repository locally and ran this in the terminal to see differences between the remote main and remote dev branches:

`git rev-list --left-right --count  origin/main...origin/dev`

That command gave this result:

```
>26196c8e4299731efe943ccf6c885b0def355a44
>7a5653d58378dc94326e3c0c8b0a8c7bf95c799c
<db64d1c51a605a6f3b08b022721ee6ccd2378157
>2669db1ea04f407f9bb3a12349869e492ce43f5c

```

This means commits 26196c8e4299731efe943ccf6c885b0def355a44, 7a5653d58378dc94326e3c0c8b0a8c7bf95c799c, and 2669db1ea04f407f9bb3a12349869e492ce43f5c are ones that `dev` has, but that `main` does not yet have. If you click on "Commits" on this GitHub page, you can see these 3 commits in the pull request.

The db64d1c51a605a6f3b08b022721ee6ccd2378157 commit is one that `main` has that `dev` does not have. That commit was the result of merging `dev` to `main` last time.

**Review by ArturoDucasse — APPROVED** [review]

**Review by ArturoDucasse — COMMENTED** [review]
I had my doubts but good catch Jessie, thanks for the explanation.

Will go ahead and push the changes.

**Pull request merged**
